#!/usr/bin/env bash

DATE="$(date +%Y%m%d%H%M)"

brew install autoconf bash binutils coreutils diffutils ed findutils flex gawk \
    gnu-indent gnu-sed gnu-tar gnu-which gpatch grep gzip less m4 make nano \
    screen watch wdiff wget zip bash-completion

grep macos-setup-bash $HOME/.zprofile >&/dev/null || {
cp $HOME/.zprofile $HOME/.zprofile.macos-setup-bash.$DATE.bak
echo '
## macos-setup-bash
path=(
  /usr/local/{bin,brewbin,sbin}
  $path[@]
)
## macos-setup-bash: end
' >> $HOME/.zprofile
}

grep macos-setup-bash $HOME/.profile >&/dev/null || {
[ -e $HOME/.profile  ] && cp $HOME/.profile $HOME/.profile.macos-setup-bash.$DATE.bak
echo '
## macos-setup-bash
export PATH=/usr/local/bin:/usr/local/brewbin:/usr/local/sbin:$PATH
source $HOME/.bashrc

BREW_BIN="/usr/local/bin/brew"
if [ -f "/opt/homebrew/bin/brew" ]; then
    BREW_BIN="/opt/homebrew/bin/brew"
fi

if type "${BREW_BIN}" &> /dev/null; then
    export BREW_PREFIX="$("${BREW_BIN}" --prefix)"
    for mandir in "${BREW_PREFIX}/opt/"*"/libexec/gnuman"; do export MANPATH=$mandir:$MANPATH; done
    for mandir in "${BREW_PREFIX}/opt/"*"/share/man/man1"; do export MANPATH=$mandir:$MANPATH; done
fi
## macos-setup-bash: end
' > $HOME/.profile
}

export PATH=/usr/local/bin:$PATH

grep "$(command -v bash)" /etc/shells >&/dev/null \
    || sudo bash -c 'echo "$(command -v bash)" >> /etc/shells; ln -s /opt/homebrew/bin /usr/local/brewbin'

[ "$1" == "--use-as-default-shell" ] && {
    dscl . -read $HOME UserShell | grep bash >&/dev/null \
        || chsh -s $(command -v bash)
}

brew list autoconf bash binutils coreutils diffutils ed findutils flex gawk \
    gnu-indent gnu-sed gnu-tar gnu-which gpatch grep gzip less m4 make nano \
    screen watch wdiff wget zip \
    | grep /bin/ | gxargs -i bash -c '
        TOOL=$(basename {}); 
        CTOOL=$(echo $TOOL| sed -re s/^g//); 
        [ $TOOL == $CTOOL ] && exit; 
        BIN=/opt/homebrew/bin; 
        [ -f {} ] && [ -e $BIN/g$CTOOL ] && ln -s $BIN/$TOOL $BIN/$CTOOL 2>/dev/null'


[ -e $HOME/.inputrc ] && cp $HOME/.inputrc $HOME/.inputrc.macos-setup-bash.$DATE.bak
[ -e $HOME/.bashrc  ] && cp $HOME/.bashrc $HOME/.bashrc.macos-setup-bash.$DATE.bak

curl -sL https://raw.githubusercontent.com/docdnp/bash2mac/main/shell.inputrc -o $HOME/.inputrc
curl -sL https://raw.githubusercontent.com/docdnp/bash2mac/main/shell.bashrc  -o $HOME/.bashrc

echo "Restart your terminal window to enable bash!"
